name: ci

on:
  push:
    branches-ignore:
      - v*

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 1

      - run: make ci
