name: ci

on:
  push:
    branches-ignore:
      - v*

jobs:
  ci:
    name: ci
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: npm install
    - run: npm run compile
    - run: npm run lint
    - run: npm run test

