name: Review
on:
  pull_request: {}
  pull_request_review_comment:
    types: [created, edited]

jobs:
  codeball:
    runs-on: ubuntu-latest
    name: codeball
    steps:
      - name: codeball
        uses: sturdy-dev/codeball-action@v2
        with:
          approvePullRequests: "false"
          labelPullRequestsWhenApproved: "true"
          labelPullRequestsWhenReviewNeeded: "true"
          labelPullRequestsWhenCarefulReviewNeeded: "true"
          failJobsWhenReviewNeeded: "false"
  coderabbit:
    runs-on: ubuntu-latest
    steps:
      - uses: coderabbitai/ai-pr-reviewer@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          debug: false
          review_simple_changes: false
          review_comment_lgtm: false
